<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-07-31T10:38:46 IST" name="Default suite" finished-at="2024-07-31T10:39:21 IST" duration-ms="35197">
    <groups>
      <group name="leads">
        <method signature="CreateAndDuplicateLeadTest.createAndDuplicateLeadTest()[pri:0, instance:testNGImplementation.CreateAndDuplicateLeadTest@73e22a3d]" name="createAndDuplicateLeadTest" class="testNGImplementation.CreateAndDuplicateLeadTest"/>
      </group> <!-- leads -->
    </groups>
    <test started-at="2024-07-31T10:38:46 IST" name="Default test" finished-at="2024-07-31T10:39:21 IST" duration-ms="35197">
      <class name="testNGImplementation.CreateAndDuplicateLeadTest">
        <test-method is-config="true" signature="classConfiguration()[pri:0, instance:testNGImplementation.CreateAndDuplicateLeadTest@73e22a3d]" started-at="2024-07-31T10:38:46 IST" name="classConfiguration" finished-at="2024-07-31T10:38:51 IST" duration-ms="5451" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- classConfiguration -->
        <test-method is-config="true" signature="methodConfiguration()[pri:0, instance:testNGImplementation.CreateAndDuplicateLeadTest@73e22a3d]" started-at="2024-07-31T10:38:52 IST" name="methodConfiguration" finished-at="2024-07-31T10:38:58 IST" duration-ms="6684" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- methodConfiguration -->
        <test-method signature="createAndDuplicateLeadTest()[pri:0, instance:testNGImplementation.CreateAndDuplicateLeadTest@73e22a3d]" started-at="2024-07-31T10:38:58 IST" name="createAndDuplicateLeadTest" finished-at="2024-07-31T10:39:18 IST" duration-ms="19621" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [true] but found [false]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at testNGImplementation.CreateAndDuplicateLeadTest.createAndDuplicateLeadTest(CreateAndDuplicateLeadTest.java:51)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createAndDuplicateLeadTest -->
        <test-method is-config="true" signature="methodTeardown()[pri:0, instance:testNGImplementation.CreateAndDuplicateLeadTest@73e22a3d]" started-at="2024-07-31T10:39:18 IST" name="methodTeardown" finished-at="2024-07-31T10:39:21 IST" duration-ms="2976" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- methodTeardown -->
        <test-method is-config="true" signature="classTeardown()[pri:0, instance:testNGImplementation.CreateAndDuplicateLeadTest@73e22a3d]" started-at="2024-07-31T10:39:21 IST" name="classTeardown" finished-at="2024-07-31T10:39:21 IST" duration-ms="388" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- classTeardown -->
      </class> <!-- testNGImplementation.CreateAndDuplicateLeadTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
